### ISSUE TITLE
Correction: Add "meta" field to create_new_document function 

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/customized-voice-text-bot-for-whatsapp-telegram#1]
The create_new_document function currently only takes an ID and session ID as inputs. It would be useful to also include a **"meta"** field to store additional information about the document, such as the user's name.

```python
def create_new_document(ID: str, session_ID: str, meta: dict):
    """
    Create a new document with the specified ID, session ID and metadata in the IBM Cloudant database.
    If the document already exists, it will not create a new document.
    
    Parameters
    ----------
    ID : str
        The ID of the new document
    session_ID : str
        The session ID for the new document
    meta: dict
        The metadata for the new document 
    """
    if not verify_document_exists(ID):
        document = {
            "_id": ID,
            "conversation": [
                {
                    "session_ID": session_ID,
                }
            ],
            "meta": meta
        }
        service.create_document(db=IBM_CLOUDANT_DATABASE, document=document).get_result()
```
**Note:** You could also add some validation on the input, if you want to ensure that the meta field is properly formatted, or if session_ID is correct.

**Comment by adinanabf** [comment]
Hello @TarikKaanKoc ,

We do not intend to save any personal information from the user except the one shared during the interaction with the chatbot. Feel free to add this to your own code.

Thank you
